import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from 'eslint-config-prettier/flat';

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  prettier,
  // animate-ui sont des primitives vendored (copiées depuis le registry, comme
  // shadcn/ui) — on ne les édite pas à la main. Les règles react-hooks récentes
  // (ère React Compiler) signalent des patterns internes à ces composants ;
  // on les neutralise uniquement ici pour ne pas faire échouer le lint du code
  // applicatif. À retirer si on réécrit ces composants nous-mêmes.
  {
    files: ['components/animate-ui/**'],
    rules: {
      'react-hooks/set-state-in-effect': 'off',
      'react-hooks/refs': 'off',
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Auto-generated by varlock typegen (contains @ts-nocheck by design):
    "env.d.ts",
  ]),
]);

export default eslintConfig;
